apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        control-plane: controller-manager
    spec:
      containers:
        - command:
            - /manager
            - --metrics-bind-address=:8080
          env:
            - name: container
              value: "true"
          image: controller:latest
          name: manager
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          # TODO(user): Configure the resources accordingly based on the project requirements.
          # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          volumeMounts:
            - name: log
              mountPath: /var/log
            - name: localtime
              mountPath: /etc/localtime
            - mountPath: /manifests
              name: manifests
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
        - name: log
          hostPath:
            path: /var/log
            type: Directory
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: manifests
          emptyDir: {}

