# permissions for end users to view bkemachinetemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bkemachinetemplate-viewer-role
rules:
- apiGroups:
  - bke.bocloud.com
  resources:
  - bkemachinetemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bke.bocloud.com
  resources:
  - bkemachinetemplates/status
  verbs:
  - get
