apiVersion: bkeagent.bocloud.com/v1beta1
kind: Command
metadata:
  name: demo
spec:
  nodeName: 192.168.56.101
  # 挂起暂不执行，可阻止下个执行的指令
  suspend: false
  commands:
    - id: builtIn-cmd
      command:
        - ipv4
      type: BuiltIn
      # 当该条指令执行失败，并且达到失败重试次数时，为true则运行跳过，默认false
      backoffIgnore: false
    - id: shell-cmd
      command: ["iptables", "--table", "nat", "--list", ">", "/tmp/iptables.rule"]
      type: Shell
      # 当该条指令执行失败，并且达到失败重试次数时，为true则运行跳过，默认false
      backoffIgnore: true
    - id: k8s-cmd
      command:
        - "secret:ns/name:ro:/tmp/secret.json"
        - "configmap:ns/name:rx:shell"
        - "configmap:ns/name:rw:/tmp/iptables.rule"
      type: Kubernetes
      # 当该条指令执行失败，并且达到失败重试次数时，为true则运行跳过，默认false
      backoffIgnore: false
  # 失败后最大重试次数
  backoffLimit: 3
  # 超过此时间后，不在执行。默认600
  # activeDeadlineSecond: 1000
  # 运行完成后，超过此清理的时间则清理该任务
  ttlSecondsAfterFinished: 1000