apiVersion: bkeagent.bocloud.com/v1beta1
kind: Command
metadata:
  name: ha
spec:
  # 挂起暂不执行，可阻止下个执行的指令
  suspend: false
  commands:
    - backoffDelay: 3
      command:
        - HA
        - haNodes=master-1:172.28.100.206,master-2:172.28.100.207,master-3:172.28.100.208
        - controlPlaneEndpointPort=36443
        - controlPlaneEndpointVIP=172.28.100.250
        - imageRepo=deploy.bocloud.k8s:40443/kubernetes/
      id: bootstrap
      type: BuiltIn
  # 失败后最大重试次数
  backoffLimit: 3
  # 超过此时间后，不在执行。默认600
  # activeDeadlineSecond: 1000
  # 运行完成后，超过此清理的时间则清理该任务
  ttlSecondsAfterFinished: 1000
  nodeSelector:
    matchLabels:
      master-1: "master-1"
      master-2: "master-2"
      master-3: "master-3"