//go:build !ignore_autogenerated

/******************************************************************
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * installer is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 ******************************************************************/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckStep) DeepCopyInto(out *CheckStep) {
	*out = *in
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckStep.
func (in *CheckStep) DeepCopy() *CheckStep {
	if in == nil {
		return nil
	}
	out := new(CheckStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterUpgradeRecord) DeepCopyInto(out *ClusterUpgradeRecord) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterUpgradeRecord.
func (in *ClusterUpgradeRecord) DeepCopy() *ClusterUpgradeRecord {
	if in == nil {
		return nil
	}
	out := new(ClusterUpgradeRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVersion) DeepCopyInto(out *ClusterVersion) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVersion.
func (in *ClusterVersion) DeepCopy() *ClusterVersion {
	if in == nil {
		return nil
	}
	out := new(ClusterVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterVersion) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVersionCondition) DeepCopyInto(out *ClusterVersionCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVersionCondition.
func (in *ClusterVersionCondition) DeepCopy() *ClusterVersionCondition {
	if in == nil {
		return nil
	}
	out := new(ClusterVersionCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVersionList) DeepCopyInto(out *ClusterVersionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterVersion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVersionList.
func (in *ClusterVersionList) DeepCopy() *ClusterVersionList {
	if in == nil {
		return nil
	}
	out := new(ClusterVersionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterVersionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVersionSpec) DeepCopyInto(out *ClusterVersionSpec) {
	*out = *in
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVersionSpec.
func (in *ClusterVersionSpec) DeepCopy() *ClusterVersionSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterVersionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVersionStatus) DeepCopyInto(out *ClusterVersionStatus) {
	*out = *in
	if in.UpgradeHistory != nil {
		in, out := &in.UpgradeHistory, &out.UpgradeHistory
		*out = make([]ClusterUpgradeRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ClusterVersionCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVersionStatus.
func (in *ClusterVersionStatus) DeepCopy() *ClusterVersionStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterVersionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompatibilitySpec) DeepCopyInto(out *CompatibilitySpec) {
	*out = *in
	if in.Constraints != nil {
		in, out := &in.Constraints, &out.Constraints
		*out = make([]Constraint, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompatibilitySpec.
func (in *CompatibilitySpec) DeepCopy() *CompatibilitySpec {
	if in == nil {
		return nil
	}
	out := new(CompatibilitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentStatus) DeepCopyInto(out *ComponentStatus) {
	*out = *in
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentStatus.
func (in *ComponentStatus) DeepCopy() *ComponentStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentVersion) DeepCopyInto(out *ComponentVersion) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentVersion.
func (in *ComponentVersion) DeepCopy() *ComponentVersion {
	if in == nil {
		return nil
	}
	out := new(ComponentVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComponentVersion) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentVersionList) DeepCopyInto(out *ComponentVersionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ComponentVersion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentVersionList.
func (in *ComponentVersionList) DeepCopy() *ComponentVersionList {
	if in == nil {
		return nil
	}
	out := new(ComponentVersionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComponentVersionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentVersionSpec) DeepCopyInto(out *ComponentVersionSpec) {
	*out = *in
	if in.Inline != nil {
		in, out := &in.Inline, &out.Inline
		*out = new(InlineSpec)
		**out = **in
	}
	if in.SubComponents != nil {
		in, out := &in.SubComponents, &out.SubComponents
		*out = make([]SubComponent, len(*in))
		copy(*out, *in)
	}
	in.Compatibility.DeepCopyInto(&out.Compatibility)
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]Dependency, len(*in))
		copy(*out, *in)
	}
	out.UpgradeStrategy = in.UpgradeStrategy
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]ResourceSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentVersionSpec.
func (in *ComponentVersionSpec) DeepCopy() *ComponentVersionSpec {
	if in == nil {
		return nil
	}
	out := new(ComponentVersionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentVersionStatus) DeepCopyInto(out *ComponentVersionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentVersionStatus.
func (in *ComponentVersionStatus) DeepCopy() *ComponentVersionStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentVersionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Constraint) DeepCopyInto(out *Constraint) {
	*out = *in
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Constraint.
func (in *Constraint) DeepCopy() *Constraint {
	if in == nil {
		return nil
	}
	out := new(Constraint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dependency) DeepCopyInto(out *Dependency) {
	*out = *in
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dependency.
func (in *Dependency) DeepCopy() *Dependency {
	if in == nil {
		return nil
	}
	out := new(Dependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InlineSpec) DeepCopyInto(out *InlineSpec) {
	*out = *in
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InlineSpec.
func (in *InlineSpec) DeepCopy() *InlineSpec {
	if in == nil {
		return nil
	}
	out := new(InlineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReleaseImage) DeepCopyInto(out *ReleaseImage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReleaseImage.
func (in *ReleaseImage) DeepCopy() *ReleaseImage {
	if in == nil {
		return nil
	}
	out := new(ReleaseImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReleaseImage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReleaseImageInstallComponent) DeepCopyInto(out *ReleaseImageInstallComponent) {
	*out = *in
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReleaseImageInstallComponent.
func (in *ReleaseImageInstallComponent) DeepCopy() *ReleaseImageInstallComponent {
	if in == nil {
		return nil
	}
	out := new(ReleaseImageInstallComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReleaseImageInstallSpec) DeepCopyInto(out *ReleaseImageInstallSpec) {
	*out = *in
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]ReleaseImageInstallComponent, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReleaseImageInstallSpec.
func (in *ReleaseImageInstallSpec) DeepCopy() *ReleaseImageInstallSpec {
	if in == nil {
		return nil
	}
	out := new(ReleaseImageInstallSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReleaseImageList) DeepCopyInto(out *ReleaseImageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ReleaseImage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReleaseImageList.
func (in *ReleaseImageList) DeepCopy() *ReleaseImageList {
	if in == nil {
		return nil
	}
	out := new(ReleaseImageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReleaseImageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReleaseImageSpec) DeepCopyInto(out *ReleaseImageSpec) {
	*out = *in
	if in.Install != nil {
		in, out := &in.Install, &out.Install
		*out = new(ReleaseImageInstallSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Upgrade != nil {
		in, out := &in.Upgrade, &out.Upgrade
		*out = new(ReleaseImageUpgradeSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReleaseImageSpec.
func (in *ReleaseImageSpec) DeepCopy() *ReleaseImageSpec {
	if in == nil {
		return nil
	}
	out := new(ReleaseImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReleaseImageStatus) DeepCopyInto(out *ReleaseImageStatus) {
	*out = *in
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]ComponentStatus, len(*in))
		copy(*out, *in)
	}
	if in.ValidatedAt != nil {
		in, out := &in.ValidatedAt, &out.ValidatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReleaseImageStatus.
func (in *ReleaseImageStatus) DeepCopy() *ReleaseImageStatus {
	if in == nil {
		return nil
	}
	out := new(ReleaseImageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReleaseImageUpgradeComponent) DeepCopyInto(out *ReleaseImageUpgradeComponent) {
	*out = *in
	if in.Inline != nil {
		in, out := &in.Inline, &out.Inline
		*out = new(ReleaseImageUpgradeInline)
		**out = **in
	}
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReleaseImageUpgradeComponent.
func (in *ReleaseImageUpgradeComponent) DeepCopy() *ReleaseImageUpgradeComponent {
	if in == nil {
		return nil
	}
	out := new(ReleaseImageUpgradeComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReleaseImageUpgradeInline) DeepCopyInto(out *ReleaseImageUpgradeInline) {
	*out = *in
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReleaseImageUpgradeInline.
func (in *ReleaseImageUpgradeInline) DeepCopy() *ReleaseImageUpgradeInline {
	if in == nil {
		return nil
	}
	out := new(ReleaseImageUpgradeInline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReleaseImageUpgradeSpec) DeepCopyInto(out *ReleaseImageUpgradeSpec) {
	*out = *in
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]ReleaseImageUpgradeComponent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReleaseImageUpgradeSpec.
func (in *ReleaseImageUpgradeSpec) DeepCopy() *ReleaseImageUpgradeSpec {
	if in == nil {
		return nil
	}
	out := new(ReleaseImageUpgradeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSpec) DeepCopyInto(out *ResourceSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.StringData != nil {
		in, out := &in.StringData, &out.StringData
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSpec.
func (in *ResourceSpec) DeepCopy() *ResourceSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubComponent) DeepCopyInto(out *SubComponent) {
	*out = *in
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubComponent.
func (in *SubComponent) DeepCopy() *SubComponent {
	if in == nil {
		return nil
	}
	out := new(SubComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradePath) DeepCopyInto(out *UpgradePath) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradePath.
func (in *UpgradePath) DeepCopy() *UpgradePath {
	if in == nil {
		return nil
	}
	out := new(UpgradePath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpgradePath) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradePathList) DeepCopyInto(out *UpgradePathList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UpgradePath, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradePathList.
func (in *UpgradePathList) DeepCopy() *UpgradePathList {
	if in == nil {
		return nil
	}
	out := new(UpgradePathList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpgradePathList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradePathRule) DeepCopyInto(out *UpgradePathRule) {
	*out = *in
	if in.PreCheck != nil {
		in, out := &in.PreCheck, &out.PreCheck
		*out = make([]CheckStep, len(*in))
		copy(*out, *in)
	}
	if in.PostCheck != nil {
		in, out := &in.PostCheck, &out.PostCheck
		*out = make([]CheckStep, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradePathRule.
func (in *UpgradePathRule) DeepCopy() *UpgradePathRule {
	if in == nil {
		return nil
	}
	out := new(UpgradePathRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradePathSpec) DeepCopyInto(out *UpgradePathSpec) {
	*out = *in
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]UpgradePathRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]VersionEntry, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradePathSpec.
func (in *UpgradePathSpec) DeepCopy() *UpgradePathSpec {
	if in == nil {
		return nil
	}
	out := new(UpgradePathSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradePathStatus) DeepCopyInto(out *UpgradePathStatus) {
	*out = *in
	if in.LastCheckedAt != nil {
		in, out := &in.LastCheckedAt, &out.LastCheckedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradePathStatus.
func (in *UpgradePathStatus) DeepCopy() *UpgradePathStatus {
	if in == nil {
		return nil
	}
	out := new(UpgradePathStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeStrategySpec) DeepCopyInto(out *UpgradeStrategySpec) {
	*out = *in
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeStrategySpec.
func (in *UpgradeStrategySpec) DeepCopy() *UpgradeStrategySpec {
	if in == nil {
		return nil
	}
	out := new(UpgradeStrategySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionEntry) DeepCopyInto(out *VersionEntry) {
	*out = *in
}

// DeepCopy// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionEntry.
func (in *VersionEntry) DeepCopy() *VersionEntry {
	if in == nil {
		return nil
	}
	out := new(VersionEntry)
	in.DeepCopyInto(out)
	return out
}
